export const GET_INDEX_CONTENT = 'GET_INDEX_CONTENT';
export const SHOW_MORE_INDEX = 'SHOW_MORE_INDEX';
export const GET_SIDEBAR_CONTENT = 'GET_SIDEBAR_CONTENT';
export const GET_SIDEBAR_CONTENT_PROJECT = 'GET_SIDEBAR_CONTENT_PROJECT';
export const INIT_INFO = 'INIT_INFO';
